services:
  nest_server:
    command: sh -c "cd /app && pnpm --filter=backend run build && pnpm --filter=backend run start:prod"
    healthcheck:
      start_period: 90s

  next_app:
    command: sh -c "cd /app && pnpm --filter=frontend run build && pnpm --filter=frontend run start"
    healthcheck:
      start_period: 90s
